version: "3.8"

services:
  namenode:
    image: apache/hadoop:3.3.5
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
    ports:
      - "9870:9870"
    command: ["/bin/bash", "/start-hdfs.sh"]
    networks:
      analytics:
        ipv4_address: 192.168.1.2

  datanode1:
    image: apache/hadoop:3.3.5
    container_name: datanode1
    hostname: datanode1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    ports:
      - "9864:9864"
    volumes:
      - ./hadoop_datanode1:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    command: ["/bin/bash", "/init-datanode.sh"]
    networks:
      analytics:
        ipv4_address: 192.168.1.3

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8080:8080"
    networks:
      analytics:
        ipv4_address: 192.168.1.4

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      analytics:
        ipv4_address: 192.168.1.5

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      analytics:
        ipv4_address: 192.168.1.6

volumes:
  hadoop-data:

networks:
  analytics:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24